## Vectors

In [2]:
% assign some vectors
format compact
a = [1 2 3]
b = [4 5 6]
% commas are valid as well
c = [7 8 9]

a =
     1     2     3
b =
     4     5     6
c =
     7     8     9


In [3]:
% semicolons change the dimension
d = [4;3;2]

d =
     4
     3
     2


In [4]:
% alternatively, A^-1 (transpose) is achieved with '
a'

ans =
     1
     2
     3


In [5]:
% access to items in a vector are indexed from 1-N
a(2)
d(1)

ans =
     2
ans =
     4


#### Calculations

In [6]:
a = [1 2 3 4 5];
b = [6 7 8 9 10];

In [7]:
a + b     % add

ans =
     7     9    11    13    15


In [8]:
a - b     % subtract

ans =
    -5    -5    -5    -5    -5


In [9]:
10 * a    % scalar multiply

ans =
    10    20    30    40    50


In [10]:
% Dot Product uses the dot(A, B) function
dot(a,b)

% we can do the same with transpose
a * b'

ans =
   130
ans =
   130


In [11]:
% Cross Product uses the cross(A,B) function
clear all
a = [1 2 3];
b = [4 5 6];
cross(a,b)

ans =
    -3     6    -3


In [12]:
% for long vectors, it is useful to get the length (number of elements);
clear all
a = [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17];
length(a)

ans =
    17


In [13]:
% all the elements of a vector can be added with sum(A) function
sum(a)

ans =
   153


In [14]:
% this is useful for averages
sum(a)/length(a)

ans =
     9


In [15]:
% min and max
min(a)
max(a)

ans =
     1
ans =
    17


#### Extraction and Creation

In [16]:
% extraction of parts of a vector 
a

a =
  Columns 1 through 13
     1     2     3     4     5     6     7     8     9    10    11    12    13
  Columns 14 through 17
    14    15    16    17


In [17]:
a = 1:10

a =
     1     2     3     4     5     6     7     8     9    10


In [18]:
b = 1:6

b =
     1     2     3     4     5     6


In [19]:
% we can also grab specific parts of a vector
q = a(6:10)

q =
     6     7     8     9    10


In [20]:
% a:n:b - this means go from a to b in n-increments 
c = 1:2:10

c =
     1     3     5     7     9


In [21]:
% this is useful for automatically making large vectors
t = 0:0.1:10;  % output suppressed to save space!!!
length(t)

ans =
   101


In [22]:
% another way to make a vector is linspace(a,b)
% make a vector exactly 100 elements evenly spaced from a to b
linspace(1,100);

In [23]:
% we can also specify how many elements we want by adding a 3rd parameter
a = linspace(1,50,5)
length(a)
mean(a)
sum(a)

a =
    1.0000   13.2500   25.5000   37.7500   50.0000
ans =
     5
ans =
   25.5000
ans =
  127.5000


In [24]:
% some more ways to create vectors
clear all
a=[2 4 6 8 10 12];
b=[1 3 5 7 9 11 13 15 17 19];  % notice that they are different sizes
c=a(3:5)                       % grab some of a
d=b(7:10)                      % grab some of b
result = [c d]                 % combine into 1 vector

c =
     6     8    10
d =
    13    15    17    19
result =
     6     8    10    13    15    17    19


In [25]:
% we can keep adding more to it
result = [c d linspace(10,15,3)]

result =
  Columns 1 through 7
    6.0000    8.0000   10.0000   13.0000   15.0000   17.0000   19.0000
  Columns 8 through 10
   10.0000   12.5000   15.0000


#### Additional Operations

In [26]:
% if we want to multiply each element such as a(1)*b(1), a(2)*b(2), a(3)*b(3), etc.
% we can do this by adding a dot/period to the first operand
a=[1 0 1 1 0 1];
b=[1 1 0 0 1 1];
a.*b

ans =
     1     0     0     0     0     1


In [27]:
% we can also use this with division
a./b

ans =
     1     0   Inf   Inf     0     1


In [28]:
% most operations covered previously work here as well
clear all
a=[1 2 3 4];
b=[-5 -6 -7 -8];

In [29]:
abs(b)

ans =
     5     6     7     8


In [30]:
log(a)

ans =
         0    0.6931    1.0986    1.3863


In [31]:
exp(b)

ans =
    0.0067    0.0025    0.0009    0.0003


In [32]:
sin(a)

ans =
    0.8415    0.9093    0.1411   -0.7568


In [33]:
% for raising to a power, we have to use the dot/period just as with element-by-element mult/div
a.^2

ans =
     1     4     9    16


In [34]:
b.^a

ans =
          -5          36        -343        4096


#### Random and Automatic Generations

In [35]:
% the rand function can generate random numbers
rand

ans =
    0.8147


In [36]:
rand

ans =
    0.9058


In [37]:
% we can extend this to vectors by using rand(m,n) where
% m is the # of rows and n is # of columns
rand(1,5)

ans =
    0.1270    0.9134    0.6324    0.0975    0.2785


In [38]:
% so, we can also get random matrices (vectors are actually matrices as well)
rand(3,3)

ans =
    0.5469    0.1576    0.4854
    0.9575    0.9706    0.8003
    0.9649    0.9572    0.1419


In [39]:
% if you need all ones, use the ones function
ones(1,3)

ans =
     1     1     1


In [40]:
ones(3)

ans =
     1     1     1
     1     1     1
     1     1     1


In [41]:
% also zeros
zeros(1,3)

ans =
     0     0     0


In [42]:
% random permutations is another useful function
randperm(5)  % random permutation of 1-5

ans =
     1     5     3     2     4


In [43]:
% random permutation of 3 numbers from 1-100
randperm(100,3)

ans =
     4    85    92


In [44]:
% we also can sort vectors
sort(ans)

ans =
     4    85    92


#### Statistical Analysis

In [45]:
clear all
data=[10 23 45 63 8 0.3 79 435 0.003];

In [46]:
mean(data)

ans =
   73.7003


In [47]:
median(data)

ans =
    23


In [48]:
std(data) % standard deviation

ans =
  138.4140


In [49]:
var(data) % variance

ans =
   1.9158e+04


In [50]:
sqrt(var(data)) % standard deviation

ans =
  138.4140
